INSERT INTO clients (company_name, contact_name, email, phone, discount) VALUES ('Redwood Coast Chamber of Commerce', 'Colin', 'r3c@gmail.com', 7078824499, 0.25), ('Irish Beach Rental Agency', 'Mack', 'ibic@gmail.com', 7078821235, 0.20), ('Edge & Center', 'Greg Hagaman', 'hagaman@gmail.com', 7078823938, 0.40), ('Cowboy Chronic', 'Forest', 'cowboychronic@gmail.com', 7073578492, 0.15);

INSERT INTO projects (client_id, name, status, payment_method, total, bundle_name, bundle_id, services, start_date, due_date) VALUES (1, 'RCCC Brand Refresh', 1, 1, 2000, 'Startup', 1, '{"WB101"}', '2018-01-15', '2018-05-01'), (2, 'IBIC Logo Update', 1, 2, 1200, 'Startup', 1, '{"WB101"}', '2018-02-10', '2018-06-02'), (3, 'Brand Initialization', 1, 3, 4200, 'Startup', 1, '{"WB101"}', '2018-01-01', '2018-04-25'), (4, 'Cowboy Chronic Upgrade', 1, 1, 6000, 'Enterprise', 3, '{"WB101", "WB201", "WB301"}', '2018-01-26', '2018-05-29');

INSERT INTO bundles (name, description, price, discount, popularity) VALUES ('Custom', 'This is the custom bundle.', NULL, 0.20, 0), ('Starter', 'This is the starter bundle.', 1800, 0.25, 2), ('Accelerator', 'This is the accelerator bundle.', 3000, 0.33, 1), ('Turbo', 'This is the turbo bundle.', 6000, 0.50, 3);

INSERT INTO services (service_code, name, description, price, capacity) VALUES ('WB101', 'Hourly Web Services', 'This is where the description will go for Hourly Web Services.', 80, true), ('WB201', 'Monthly Web Services', 'This is where the description will go for Monthly Web Services.', 600, true), ('WB301', 'Quarterly Web Servies', 'This is where the description will go for Quarterly Web Services.', 700, true);

INSERT INTO goals (name, description, category) VALUES ('Create Website', 'This is a description homie, 1', 'CREATE'), ('Update Website', 'This is a description homie, 2', 'UPDATE'), ('Produce Visual Content', 'This is a description homie, 3', 'CREATE'), ('Remote IT Services', 'This is a description homie, 4', 'OTHER'), ('Build Device', 'This is a description homie, 5', 'CREATE'), ('Install Network', 'This is a description homie, 6', 'CREATE'), ('Business Development for Online Growth', 'This is a description homie, 7', 'UPDATE'), ('Create Brand Assets', 'This is a description homie, 8', 'CREATE'), ('Market Online', 'This is a description homie, 9', 'MANAGE'), ('Create Logo', 'This is a description homie, 10', 'CREATE'), ('Update Logo', 'This is a description homie, 11', 'UPDATE'), ('Produce Marketing Graphics', 'This is a description homie, 12', 'CREATE'), ('Design Website', 'This is a description homie, 13', 'CREATE'), ('Broadcast Event', 'This is a description homie, 14', 'OTHER'), ('Post-Produce Visual Content', 'This is a description homie, 15', 'OTHER'), ('Manage Data or Device', 'This is a description homie, 16', 'MANAGE');

INSERT INTO bundleRelations (bundle_id, service_id) VALUES (1, 2), (2, 1), (2, 3), (3, 1), (3, 2), (3, 3);
INSERT INTO goalRelations (goal_id, service_id) VALUES (1, 2), (2, 1), (2, 3), (3, 1), (3, 2), (3, 3), (4, 2);
